### PR TITLE
Omit the print of AWS credentials in the console unless verbose option is passed

### PR DESCRIPTION
**Pull request by sadok-f**
Hi,
Thank you for this repo, we're using it as our sso cli tool to access AWS accounts.

we had to modify it a bit to omit the print of the AWS credentials to the console while authenticating.
This MR contains the code change for that, it doesn't change the default behaviour.

Thanks.
Sadok

### CODE REVIEW

**Comment by sadok-f** [comment]
@matwhite can you review this PR, appreciate that :)
thanks

**Comment by maxtacu** [comment]
hey @sadok-f You have typo in some places: `silent`, `slient` and it seems like it is duplicating the verbose mode

**Comment by sadok-f** [comment]
Hey @maxtacu , thank you for checking, I've modified my PR.
now with the verbose option, the AWS credentials will be printed to the console.

**Comment by maxtacu** [comment]
@sadok-f Nice thanks! LGTM. Can you also please just increment the PATCH version and add changes to the CHANGELOG?

**Comment by maxtacu** [comment]
p.s. app version is set in `oktaawscli/version.py`. Please increment only PATCH version to `0.5.1`

**Comment by sadok-f** [comment]
Version incremented and changes added to CHANGELOG

**Pull request merged**
